// <auto-generated />
using System;
using HPM_System.EventService.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HPM_System.EventService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211180119_CorrectionEventsModelForExternalServices")]
    partial class CorrectionEventsModelForExternalServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HPM_System.EventService.Models.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Place")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventDateTime")
                        .HasDatabaseName("IX_Event_EventDateTime");

                    b.HasIndex("Title");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("HPM_System.EventService.Models.EventParticipant", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("EventId1")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Reminder24hSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Reminder24hSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Reminder2hSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Reminder2hSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SubscribedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("EventId1");

                    b.HasIndex("InvitedAt");

                    b.HasIndex("IsSubscribed");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "IsSubscribed");

                    b.HasIndex("EventId", "IsSubscribed", "Reminder24hSent")
                        .HasDatabaseName("IX_EventParticipant_24hReminder");

                    b.HasIndex("EventId", "IsSubscribed", "Reminder2hSent")
                        .HasDatabaseName("IX_EventParticipant_2hReminder");

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("HPM_System.EventService.Models.EventParticipant", b =>
                {
                    b.HasOne("HPM_System.EventService.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HPM_System.EventService.Models.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("HPM_System.EventService.Models.Event", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
