// <auto-generated />
using System;
using HPM_System.ApartmentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HPMSystem.ApartmentService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251011143525_EntranceNumberToApartment")]
    partial class EntranceNumberToApartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HPM_System.ApartmentService.Models.Apartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("EntranceNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer");

                    b.Property<long>("HouseId")
                        .HasColumnType("bigint");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("NumbersOfRooms")
                        .HasColumnType("integer");

                    b.Property<decimal>("ResidentialArea")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalArea")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Apartment");
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.ApartmentUser", b =>
                {
                    b.Property<long>("ApartmentId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Share")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasDefaultValue(0m);

                    b.HasKey("ApartmentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ApartmentUsers");
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.ApartmentUserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ApartmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("ApartmentId", "UserId", "StatusId")
                        .IsUnique();

                    b.ToTable("ApartmentUserStatuses");
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.District", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("HouseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.HasIndex("ParentId");

                    b.ToTable("District");
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.House", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("ApartmentsArea")
                        .HasColumnType("double precision");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Entrances")
                        .HasColumnType("integer");

                    b.Property<int>("Floors")
                        .HasColumnType("integer");

                    b.Property<bool>("HasElectricity")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasElevator")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasGas")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("HeadId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsApartmentBuilding")
                        .HasColumnType("boolean");

                    b.Property<double?>("LandArea")
                        .HasColumnType("double precision");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PostIndex")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("TotalArea")
                        .HasColumnType("double precision");

                    b.Property<int>("builtYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeadId");

                    b.HasIndex("City", "Street", "Number")
                        .IsUnique();

                    b.ToTable("House");
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Владелец"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Жилец"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Прописан"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Временно проживающий"
                        });
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.Apartment", b =>
                {
                    b.HasOne("HPM_System.ApartmentService.Models.House", null)
                        .WithMany("Apartments")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.ApartmentUser", b =>
                {
                    b.HasOne("HPM_System.ApartmentService.Models.Apartment", "Apartment")
                        .WithMany("Users")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HPM_System.ApartmentService.Models.User", "User")
                        .WithMany("Apartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.ApartmentUserStatus", b =>
                {
                    b.HasOne("HPM_System.ApartmentService.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HPM_System.ApartmentService.Models.ApartmentUser", "ApartmentUser")
                        .WithMany("Statuses")
                        .HasForeignKey("ApartmentId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.District", b =>
                {
                    b.HasOne("HPM_System.ApartmentService.Models.House", null)
                        .WithMany("Districts")
                        .HasForeignKey("HouseId");

                    b.HasOne("HPM_System.ApartmentService.Models.District", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.Apartment", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.ApartmentUser", b =>
                {
                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.House", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Districts");
                });

            modelBuilder.Entity("HPM_System.ApartmentService.Models.User", b =>
                {
                    b.Navigation("Apartments");
                });
#pragma warning restore 612, 618
        }
    }
}
